//! Compiles `assets/ascii/index.toml` and the art files next to it into a
//! static table, so the finished binary carries every logo with no data dir.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Index {
    #[serde(default)]
    logo: Vec<Logo>,
}

#[derive(Deserialize)]
struct Logo {
    key: String,
    names: Vec<String>,
    colors: Vec<String>,
    file: String,
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ascii = manifest.join("assets/ascii");
    let index_path = ascii.join("index.toml");

    println!("cargo:rerun-if-changed={}", index_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&index_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", index_path.display()));
    let index: Index = toml::from_str(&raw)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", index_path.display()));

    // Keys are unique and sorted so lookups can binary-search the alias map.
    let mut aliases: BTreeMap<String, usize> = BTreeMap::new();
    let mut out = String::new();

    out.push_str("// @generated by build.rs - do not edit.\n\n");
    let _ = writeln!(out, "pub static LOGOS: [RawLogo; {}] = [", index.logo.len());

    for (i, logo) in index.logo.iter().enumerate() {
        let art = ascii.join(&logo.file);
        println!("cargo:rerun-if-changed={}", art.display());
        if !art.is_file() {
            panic!("missing art file {} for logo {}", art.display(), logo.key);
        }

        for name in &logo.names {
            // Lookup is case-insensitive; normalise on the way in.
            aliases.insert(normalise(name), i);
        }
        aliases.insert(normalise(&logo.key), i);

        let _ = writeln!(out, "    RawLogo {{");
        let _ = writeln!(out, "        key: {:?},", logo.key);
        let _ = writeln!(out, "        names: &{:?},", logo.names);
        let _ = writeln!(out, "        colors: &{:?},", logo.colors);
        let _ = writeln!(out, "        art: include_str!({:?}),", path_literal(&art));
        let _ = writeln!(out, "    }},");
    }
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "pub static ALIASES: [(&str, usize); {}] = [",
        aliases.len()
    );
    for (alias, idx) in &aliases {
        let _ = writeln!(out, "    ({alias:?}, {idx}),");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("logo_data.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// Alias keys are compared lowercased with separators removed, so that
/// "Pop!_OS", "pop_os" and "popos" all resolve to the same logo.
fn normalise(s: &str) -> String {
    s.chars()
        .filter(|c| c.is_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

fn path_literal(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}
